api_path: http://{call_address}/transport/response/{serial_number}
buad_rate: 9600
call_address: 192.168.0.128:8000
hops: 5
max_packet_size: 140
net_id: 0
port: /dev/ttyAMA0
serial_number: '1234.1234'
timeout: 0.25
